---
title: "Workflow.rmd"
author: "Rutuja Chitra-Tarak"
date: "12/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### Met data files

Code/0.01_Checking_met_data.R 

### Generate parameter files

(a) FATES param files dependencies:
Parameter range for roob_b parameters are generated here: 3.090_root_parameters_b.R
Can verify that different root a can give same b: data-raw/estimation of root_b_par_same_b_for_different as.xlsx
Other ranges are based on literature or Kunert's data

(b) ELM param files dependencies:
fpi_max ranges are generated from here: 
## First throughfall from Zimmermann et al and rain data from STRI at Lutz are linked: Code/0.03_Throughfall.R 
## As rainfall data is not given in Zimmermann and throughfall data is collected for rainfall events (duration, amount and gap between events), rainfall that composes those events are inferred in Excel.
And range of interception found for events > 10 mm: data-raw/throughfall_rain_hourly_for_inspection_new.xlsx

(c) Surface data files dependencies:
Soil testure data and soil organic content data is gathered and defined here:
Code/3.2_Surfdata_texture_options.R
But these are not used by the model as it is forced with 
(1) soil characteristic curves (SWC to Matric potential) using Stephan Kupers' data (Yilin's egquation), as well as, bci.hydromet/data-raw/soil_retention_curves_stephan.R
(2) soil hydraulic conductivity, using Godsey & Stallard et al defined here: Code/3.2.5_Surfdata_Ksat_obs_and_bootstrapped_param.R

Surface data for ELM, ELM parameters and FATES paramater files 
Code/3.1_Generate_parameter files.R

These are transfer to the server.

Follow Google Doc 3.0_Running ELM-FATES with parameter ensembles @ Shared drives/Rutuja_work/web_only/ <https://docs.google.com/document/d/1qqbkQGHMG8BMfrUejUlkBU3PvUqPuW0Pc6CBLBQzZZk/edit#heading=h.gjdgxs>
Thus run ensembles and extract simulations on the server with Code/2.0_main.R (that sources Code/1.0_fun_extract.R) and transfer back to the desktop storing at a specific dated location such as data-raw/extract/2019-10-14_5000

Use Code/4.1_ELM-FATES_output.R to generate RMSE or Rsq values between simulations and hydrological observations, plot best-fits for individual fluxes and run sensitivity analyses. These outputs are compiled in individual-flux-best-fits.html and Report.html

Outputs from trials such as 
4.1_ELM-FATES_output_trial_leafage_fdrought.R, 4.1_ELM-FATES_output_trial2.R,
4.1_ELM-FATES_output_trial_tlai_reduction.R, are compiled in leafage_fdrought.html, Effect-of-bbslope---VCmax.html or Max-Rooting-Depth-effect.html

Use Code/4.2_ELM-FATES_params_bestfit.R to generate objective function to choose best-fit simulations that fits all individual fluxes well (QRUNOFF, AET, Soil moisture by depth)

Confirm that individual fluxes are well captured by thus chosen best-fits:  Code/4.3_ELM-FATES_output_bestfit.R

Now for the chosen best-fits re-run simulations covering the entire time-period of 1985-2018
Follow Google Doc 4.0_Running ELM-FATES for best-fit parameter (and  Code/5.0_Prep_for_Best-fit_case_runs.R to generate par.sam numbers seperated by commas) ensembles<https://docs.google.com/document/d/1q6gC5nPrlcnaxl7WvHHVr-Yzu2xBZlIu4b1OcHdGdOc/edit#heading=h.mn9abqhwo6l5>

Extract data on server and transfer to desktop at location such as
data-raw/extract/2019-10-14_5000/best-fits, 
Then extract and save full swp, btran time-series to be used with the package.
R/6.0_ELM-FATES_full best-fit_swp.R

Plot the entire time-series of SWC, SWP and ELM-FATES generated BTRAN for best-fit simulations.
Code/6.1_Plotting best-fits_full.R
